project:
  type: website
  output-dir: docs

website:
  title: "Frederik Lange"
  page-navigation: true
  favicon: "images/logo_frederik.jpg"

  navbar:
    background: "white"
    foreground: dark
    align: center
    search: true
    pinned: true
    logo: "images/logo_frederik.jpg"

    left:
      - text: "Intro"
        href: about.qmd
      - text: "Portfolio"
        href: portfolio.qmd
      - text: "Resume"
        href: resume.qmd
    
  page-footer:
    center: This page is built with [Quarto](https://quarto.org/).
 
format:
  html:
    theme: minty
    toc: true
    css: styles.css
    code-link: true
    code-fold: show
    highlight-style: dracula
